### ISSUE TITLE
quoted namespaces make mmt crash

### ISSUE THREAD

**Issue by cmaeder** [UniFormal/MMT#113]
The double quotes in the LATIN file:

```
--- a/source/logics/dynamic/propdynlog.mmt
+++ b/source/logics/dynamic/propdynlog.mmt
@@ -1,4 +1,4 @@
-namespace "http://latin.omdoc.org/logics/syntax".^]
+namespace http://latin.omdoc.org/logics/syntax^]
```

make mmt crash with:

```
archive: entering /home/travis/build/KWARC/MMT/LATIN/source/logics/dynamic
Exception in thread "main" java.net.URISyntaxException: Illegal character in scheme name at index 0: "http://latin.omdoc.org/logics/syntax%22.
    at java.net.URI$Parser.fail(URI.java:2848)
    at java.net.URI$Parser.checkChars(URI.java:3021)
    at java.net.URI$Parser.checkChar(URI.java:3031)
    at java.net.URI$Parser.parse(URI.java:3047)
    at java.net.URI.<init>(URI.java:746)
    at info.kwarc.mmt.api.utils.URI.toJava(URI.scala:111)
    at info.kwarc.mmt.api.utils.URI.resolve(URI.scala:90)
    at info.kwarc.mmt.api.Path$.mergeD(Path.scala:324)
    at info.kwarc.mmt.api.Path$.parse(Path.scala:351)
    at info.kwarc.mmt.api.Path$.parse(Path.scala:321)
    at info.kwarc.mmt.api.Path$.parseD(Path.scala:408)
    at info.kwarc.mmt.api.parser.KeywordBasedParser.readDPath(StructureParser.scala:213)
    at info.kwarc.mmt.api.parser.KeywordBasedParser.info$kwarc$mmt$api$parser$KeywordBasedParser$$readInDocument(StructureParser.scala:344)
    at info.kwarc.mmt.api.parser.KeywordBasedParser$$anonfun$apply$1.apply$mcV$sp(StructureParser.scala:170)
    at info.kwarc.mmt.api.parser.KeywordBasedParser$$anonfun$apply$1.apply(StructureParser.scala:170)
    at info.kwarc.mmt.api.parser.KeywordBasedParser$$anonfun$apply$1.apply(StructureParser.scala:170)
    at info.kwarc.mmt.api.frontend.Logger$class.logGroup(Log.scala:23)
    at info.kwarc.mmt.api.parser.Parser.logGroup(Parser.scala:205)
    at info.kwarc.mmt.api.parser.KeywordBasedParser.apply(StructureParser.scala:169)
    at info.kwarc.mmt.api.parser.KeywordBasedParser.apply(StructureParser.scala:160)
    at info.kwarc.mmt.api.parser.MMTStructureEstimator$class.estimateResult(StructureParser.scala:959)
    at info.kwarc.mmt.api.frontend.ExtensionManager$$anon$1.estimateResult(ExtensionManager.scala:233)
    at info.kwarc.mmt.api.archives.TraversingBuildTarget$$anonfun$buildAux$3.apply(BuildTarget.scala:346)
    at info.kwarc.mmt.api.archives.TraversingBuildTarget$$anonfun$buildAux$3.apply(BuildTarget.scala:342)
    at info.kwarc.mmt.api.archives.Archive.traverse(Archive.scala:128)
    at info.kwarc.mmt.api.archives.Archive.info$kwarc$mmt$api$archives$Archive$$recurse$1(Archive.scala:109)
    at info.kwarc.mmt.api.archives.Archive$$anonfun$4.apply(Archive.scala:116)
    at info.kwarc.mmt.api.archives.Archive$$anonfun$4.apply(Archive.scala:116)
    at scala.collection.immutable.List.flatMap(List.scala:327)
    at info.kwarc.mmt.api.archives.Archive.traverse(Archive.scala:116)
    at info.kwarc.mmt.api.archives.Archive.info$kwarc$mmt$api$archives$Archive$$recurse$1(Archive.scala:109)
    at info.kwarc.mmt.api.archives.Archive$$anonfun$4.apply(Archive.scala:116)
    at info.kwarc.mmt.api.archives.Archive$$anonfun$4.apply(Archive.scala:116)
    at scala.collection.immutable.List.flatMap(List.scala:327)
    at info.kwarc.mmt.api.archives.Archive.traverse(Archive.scala:116)
    at info.kwarc.mmt.api.archives.Archive.info$kwarc$mmt$api$archives$Archive$$recurse$1(Archive.scala:109)
    at info.kwarc.mmt.api.archives.Archive$$anonfun$4.apply(Archive.scala:116)
    at info.kwarc.mmt.api.archives.Archive$$anonfun$4.apply(Archive.scala:116)
    at scala.collection.immutable.List.flatMap(List.scala:327)
    at info.kwarc.mmt.api.archives.Archive.traverse(Archive.scala:116)
    at info.kwarc.mmt.api.archives.TraversingBuildTarget.buildAux(BuildTarget.scala:342)
    at info.kwarc.mmt.api.archives.TraversingBuildTarget.makeBuildTasks(BuildTarget.scala:333)
    at info.kwarc.mmt.api.archives.TraversingBuildTarget.build(BuildTarget.scala:325)
    at info.kwarc.mmt.api.archives.TraversingBuildTarget.build(BuildTarget.scala:321)
    at info.kwarc.mmt.api.archives.BuildTarget.apply(BuildTarget.scala:184)
    at info.kwarc.mmt.api.frontend.ActionHandling$$anonfun$archiveBuildAction$1.apply(ActionHandling.scala:304)
    at info.kwarc.mmt.api.frontend.ActionHandling$$anonfun$archiveBuildAction$1.apply(ActionHandling.scala:281)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at info.kwarc.mmt.api.frontend.ActionHandling$class.archiveBuildAction(ActionHandling.scala:281)
    at info.kwarc.mmt.api.frontend.Controller.archiveBuildAction(Controller.scala:64)
    at info.kwarc.mmt.api.frontend.ActionHandling$class.handle(ActionHandling.scala:60)
    at info.kwarc.mmt.api.frontend.Controller.handle(Controller.scala:64)
    at info.kwarc.mmt.api.frontend.ActionHandling$$anonfun$doAction$1.apply(ActionHandling.scala:354)
    at info.kwarc.mmt.api.frontend.ActionHandling$$anonfun$doAction$1.apply(ActionHandling.scala:354)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at info.kwarc.mmt.api.frontend.ActionHandling$class.doAction(ActionHandling.scala:354)
    at info.kwarc.mmt.api.frontend.Controller.doAction(Controller.scala:64)
    at info.kwarc.mmt.api.frontend.ActionHandling$$anonfun$execFileAction$2.apply(ActionHandling.scala:325)
    at info.kwarc.mmt.api.frontend.ActionHandling$$anonfun$execFileAction$2.apply(ActionHandling.scala:324)
    at scala.Option.foreach(Option.scala:257)
    at info.kwarc.mmt.api.frontend.ActionHandling$class.execFileAction(ActionHandling.scala:324)
    at info.kwarc.mmt.api.frontend.Controller.execFileAction(Controller.scala:64)
    at info.kwarc.mmt.api.frontend.ActionHandling$class.handle(ActionHandling.scala:103)
    at info.kwarc.mmt.api.frontend.Controller.handle(Controller.scala:64)
    at info.kwarc.mmt.api.frontend.ActionHandling$class.handleLine(ActionHandling.scala:27)
    at info.kwarc.mmt.api.frontend.Controller.handleLine(Controller.scala:64)
    at info.kwarc.mmt.api.frontend.Shell$$anonfun$mainRaw$6.apply(Shell.scala:156)
    at info.kwarc.mmt.api.frontend.Shell$$anonfun$mainRaw$6.apply(Shell.scala:156)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at info.kwarc.mmt.api.frontend.Shell.mainRaw(Shell.scala:156)
    at info.kwarc.mmt.api.frontend.Shell.main(Shell.scala:72)
    at info.kwarc.mmt.api.frontend.Run.main(Shell.scala)
```

**Comment by kohlhase** [comment]
make a better error message.

**Comment by florian-rabe** [comment]
Not sure if this is still the case or if MMT catches the exception by now.

**Comment by Jazzpirate** [comment]
Reproduced; seems to be fixed
