### ISSUE TITLE
NullPointerException while starting MMT

### ISSUE THREAD

**Issue by doofyman** [UniFormal/MMT#222]
@florian-rabe 
Running "java -jar mmt.jar" on macOS
Error message:

Exception in thread "main" java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:129)
	at scala.io.BufferedSource.reader(BufferedSource.scala:24)
	at scala.io.BufferedSource.bufferedReader(BufferedSource.scala:25)
	at scala.io.BufferedSource.scala$io$BufferedSource$$charReader$lzycompute(BufferedSource.scala:35)
	at scala.io.BufferedSource.scala$io$BufferedSource$$charReader(BufferedSource.scala:33)
	at scala.io.BufferedSource.scala$io$BufferedSource$$decachedReader(BufferedSource.scala:62)
	at scala.io.BufferedSource.mkString(BufferedSource.scala:91)
	at info.kwarc.mmt.api.utils.package$.readFullStream(package.scala:94)
	at info.kwarc.mmt.api.utils.MMTSystem$.getResourceAsString(System.scala:83)
	at info.kwarc.mmt.api.frontend.Controller.init(Controller.scala:207)
	at info.kwarc.mmt.api.frontend.Controller.<init>(Controller.scala:211)
	at info.kwarc.mmt.api.frontend.Shell.controller$lzycompute(Shell.scala:40)
	at info.kwarc.mmt.api.frontend.Shell.controller(Shell.scala:40)
	at info.kwarc.mmt.api.frontend.Shell.deferToExtension(Shell.scala:78)
	at info.kwarc.mmt.api.frontend.Shell.mainRaw(Shell.scala:119)
	at info.kwarc.mmt.api.frontend.Shell.main(Shell.scala:54)
	at info.kwarc.mmt.api.frontend.Run.main(Shell.scala)

**Comment by florian-rabe** [comment]
That should not happen.

Can you build mmt on the devel branch and check what error message you get?

**Comment by doofyman** [comment]
I moved the folder to Desktop and tried it again... problem solved.

Probably there is some bug which causes trouble when the path name is too long or contains certain characters.

**Comment by tkw1536** [comment]
I would suggest we actually leave this issue open - it suggests something weird going on in ``getResourceAsString``.
 @doofyman Which exact path was the jar located on? Maybe we can try to reproduce this error and fix it.

**Comment by doofyman** [comment]
The path looks like this:
..../xxxx/xxxx/xxxx xxxx/xxxx xxxx xxxx xxxx/MMT-master/deploy/mmt.jar

By the way, the devel version didn't work under the same directory either. I put it on Desktop and it worked.

**Comment by kohlhase** [comment]
make a test for this.

**Comment by florian-rabe** [comment]
Maybe spaces in file names need to be escaped in a mac-specific way.

**Comment by kohlhase** [comment]
I can help test this.

**Comment by tkw1536** [comment]
@kohlhase Is this issue actively affecting you? I am running on Mac as well, but so far have not encountered it.

**Comment by kohlhase** [comment]
no it does not affect me. I had forgotten that you have a Mac as well, and just wanted to help

**Comment by doofyman** [comment]
Hi, it seems like the issue was fixed. I think originally it couldn't work with path names containing spaces, but I just tested it and now it seems to work with only some warnings, but no errors.

**Comment by tkw1536** [comment]
in that case I will close this issue.
