### ISSUE TITLE
sbt deploy on master version does not work for JDK 9.0.1 on MacOS

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#277]
I retried `sbt deploy` after updating master, and (after loads of warnings) I get 
```
[error] ## Exception when compiling 11 sources to /Users/kohlhase/vc/git/github.com/UniFormal/MMT/src/mmt-oeis/target/scala-2.11/classes
[error] GC overhead limit exceeded
[error] scala.collection.immutable.Set$Set2.$plus(Set.scala:120)
[error] scala.collection.immutable.Set$Set2.$plus(Set.scala:114)
[error] scala.collection.mutable.SetBuilder.$plus$eq(SetBuilder.scala:22)
[error] scala.collection.mutable.SetBuilder.$plus$eq(SetBuilder.scala:20)
[error] scala.collection.generic.Growable$$anonfun$$plus$plus$eq$1.apply(Growable.scala:59)
[error] scala.collection.generic.Growable$$anonfun$$plus$plus$eq$1.apply(Growable.scala:59)
[error] scala.reflect.internal.Scopes$Scope.foreach(Scopes.scala:373)
[error] scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
[error] scala.collection.mutable.SetBuilder.$plus$plus$eq(SetBuilder.scala:20)
[error] scala.collection.TraversableLike$class.to(TraversableLike.scala:590)
[error] scala.reflect.internal.Scopes$Scope.to(Scopes.scala:51)
[error] scala.collection.TraversableOnce$class.toSet(TraversableOnce.scala:304)
[error] scala.reflect.internal.Scopes$Scope.toSet(Scopes.scala:51)
[error] scala.tools.nsc.transform.Constructors$OmittablesHelper$class.populateOmittables(Constructors.scala:171)
[error] scala.tools.nsc.transform.Constructors$TemplateTransformer.populateOmittables(Constructors.scala:461)
[error] scala.tools.nsc.transform.Constructors$TemplateTransformer.<init>(Constructors.scala:679)
[error] scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:84)
[error] scala.tools.nsc.transform.Constructors$TemplateTransformer.<init>(Constructors.scala:639)
[error] scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:84)
[error] scala.tools.nsc.transform.Constructors$TemplateTransformer.<init>(Constructors.scala:639)
[error] scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:84)
[error] scala.tools.nsc.transform.Constructors$TemplateTransformer.<init>(Constructors.scala:639)
[error] scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:84)
[error] scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:30)
[error] scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2589)
[error] scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2587)
[error] scala.collection.immutable.List.loop$1(List.scala:176)
[error] scala.collection.immutable.List.mapConserve(List.scala:200)
[error] scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
[error] scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1426)
[error] scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1426)
[error] scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
[error]            
[warn] /Users/kohlhase/vc/git/github.com/UniFormal/MMT/src/mmt-owl/src/info/kwarc/mmt/owl/AddImpacts.scala:27:17: match may not be exhaustive.
[warn] It would fail on the following inputs: CPath(DPath(_), _), CPath(MPath(_, _), _), DPath(_), MPath(_, _)
[warn]     val gname = path match {
[warn]                 ^
[warn] one warning found
[info] Done compiling.
[warn] /Users/kohlhase/vc/git/github.com/UniFormal/MMT/src/mmt-owl/src/info/kwarc/mmt/owl/AddImpacts.scala:109:56: match may not be exhaustive.
[warn] It would fail on the following inputs: (_ : info.kwarc.mmt.api.moc.ChangeDeclaration), (_ : info.kwarc.mmt.api.moc.ChangeModule), Add(), AddContent(), Delete(), DeleteContent(), PragmaticChange(_, _, _, _, _), UpdateContent(), UpdateMetadata(_, _, _, _)
[warn]     val (changeType: String, changePath: GlobalName) = change match {
[warn]                                                        ^
[error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
[error] 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[error] 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:200)
[error] 	at sbt.Execute.next$1(Execute.scala:99)
[error] 	at sbt.Execute.processAll(Execute.scala:102)
[error] 	at sbt.Execute.runKeep(Execute.scala:79)
[error] 	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:383)
[error] 	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:382)
[error] 	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:401)
[error] 	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:96)
[error] 	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:327)
[error] 	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:94)
[error] 	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:107)
[error] 	at sbt.internal.Aggregation$.$anonfun$applyTasks$1(Aggregation.scala:64)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:121)
[error] 	at sbt.internal.Aggregation$.$anonfun$evaluatingParser$11(Aggregation.scala:216)
[error] 	at sbt.internal.Act$.$anonfun$actParser0$3(Act.scala:310)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:121)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:105)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:227)
[error] 	at sbt.State$$anon$1.process(State.scala:233)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:105)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:105)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:98)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:76)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:104)
[error] 	at sbt.xMain.run(Main.scala:71)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
[error] 	at scala.collection.immutable.Set$Set2.$plus(Set.scala:120)
[error] 	at scala.collection.immutable.Set$Set2.$plus(Set.scala:114)
[error] 	at scala.collection.mutable.SetBuilder.$plus$eq(SetBuilder.scala:22)
[error] 	at scala.collection.mutable.SetBuilder.$plus$eq(SetBuilder.scala:20)
[error] 	at scala.collection.generic.Growable$$anonfun$$plus$plus$eq$1.apply(Growable.scala:59)
[error] 	at scala.collection.generic.Growable$$anonfun$$plus$plus$eq$1.apply(Growable.scala:59)
[error] 	at scala.reflect.internal.Scopes$Scope.foreach(Scopes.scala:373)
[error] 	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
[error] 	at scala.collection.mutable.SetBuilder.$plus$plus$eq(SetBuilder.scala:20)
[error] 	at scala.collection.TraversableLike$class.to(TraversableLike.scala:590)
[error] 	at scala.reflect.internal.Scopes$Scope.to(Scopes.scala:51)
[error] 	at scala.collection.TraversableOnce$class.toSet(TraversableOnce.scala:304)
kwarc20:src kohlhase$ 
```

**Comment by kohlhase** [comment]
at least this seems a different error than last time before the release.

**Comment by tkw1536** [comment]
I haven't see this one before. My guess is that this comes from ff7ee3d18f508e3f3b4cf09194792ba33a86dfa9, but I am not sure.

**Comment by tkw1536** [comment]
See #263, closing.
