### ISSUE TITLE
Call to "http://localhost:8080/:interview/infer" not returning

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [UniFormal/MMT#302]
Whenever I try to have the type of some expression (for starters, a constant) inferred - like 
`http://localhost:8080/:interview/infer?cont=$URI$ `-
, I get no reply.

Instead, mmt shows me the following exception in the console:

> java -jar mmt.jar 
> This is the MMT shell, you may enter actions to be evaluated.
> Type 'show help' to see this message at any point, 'show help topics' to get a
> list of available help topics and 'show mmt' for information about the version
> of the mmt system you have installed.
> For more details, you may refer to the online help available at:
> 
> https://uniformal.github.io/doc/applications/shell.html
> mmt>extension info.kwarc.mmt.interviews.InterviewServer
> user: 'extension info.kwarc.mmt.interviews.InterviewServer'
> user: 'extension info.kwarc.mmt.interviews.InterviewServer' finished
> mmt>server on 8080
> user: 'server on 8080'
>   user: Server started at http://127.0.0.1:8080
> user: 'server on 8080' finished
> mmt>Exception in thread "ServerExecutorPool-0-7" java.lang.NoClassDefFoundError: info/kwarc/mmt/api/Rule$class
> 	at info.kwarc.mmt.mitm.rules.Binary.priority(Literals.scala:96)
> 	at info.kwarc.mmt.api.RuleSet.$anonfun$getOrdered$1(Rule.scala:91)
> 	at info.kwarc.mmt.api.RuleSet.$anonfun$getOrdered$1$adapted(Rule.scala:91)
> 	at scala.math.Ordering$$anon$5.compare(Ordering.scala:122)
> 	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
> 	at java.util.TimSort.sort(TimSort.java:220)
> 	at java.util.Arrays.sort(Arrays.java:1438)
> 	at scala.collection.SeqLike.sorted(SeqLike.scala:652)
> 	at scala.collection.SeqLike.sorted$(SeqLike.scala:640)
> 	at scala.collection.AbstractSeq.sorted(Seq.scala:41)
> 	at scala.collection.SeqLike.sortBy(SeqLike.scala:627)
> 	at scala.collection.SeqLike.sortBy$(SeqLike.scala:627)
> 	at scala.collection.AbstractSeq.sortBy(Seq.scala:41)
> 	at info.kwarc.mmt.api.RuleSet.getOrdered(Rule.scala:91)
> 	at info.kwarc.mmt.api.uom.UOMState.<init>(RuleBasedSimplifier.scala:19)
> 	at info.kwarc.mmt.api.uom.RuleBasedSimplifier.apply(RuleBasedSimplifier.scala:54)
> 	at info.kwarc.mmt.api.uom.Simplifier.apply(Simplifier.scala:40)
> 	at info.kwarc.mmt.api.checking.Solver.simplify(Solver.scala:1412)
> 	at info.kwarc.mmt.api.checking.Solver.substituteSolved(Solver.scala:1424)
> 	at info.kwarc.mmt.api.checking.Solver.$anonfun$inferType$20(Solver.scala:985)
> 	at scala.Option.map(Option.scala:146)
> 	at info.kwarc.mmt.api.checking.Solver.inferType(Solver.scala:985)
> 	at info.kwarc.mmt.api.checking.Solver$.infer(Solver.scala:1792)
> 	at info.kwarc.mmt.interviews.InterviewServer.apply(InterviewServer.scala:73)
> 	at info.kwarc.mmt.api.web.Server.resolveExtension(Server.scala:95)
> 	at info.kwarc.mmt.api.web.Server.resolve(Server.scala:76)
> 	at info.kwarc.mmt.api.web.Server.handleRequest(Server.scala:53)
> 	at info.kwarc.mmt.api.web.TiscafServerImplementation$RequestHandler$$anon$1.act(TiscafServerImplementation.scala:49)
> 	at tiscaf.HSimpleLet.aact(HLet.scala:166)
> 	at tiscaf.HSimpleLet.aact$(HLet.scala:165)
> 	at info.kwarc.mmt.api.web.TiscafServerImplementation$RequestHandler$$anon$1.aact(TiscafServerImplementation.scala:47)
> 	at tiscaf.HAcceptor.talk(HAcceptor.scala:246)
> 	at tiscaf.HSimplePeer.doTalkItself$1(HPeer.scala:101)
> 	at tiscaf.HSimplePeer.$anonfun$readChannel$1(HPeer.scala:114)
> 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
> 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)
> 	at scala.util.Success.$anonfun$map$1(Try.scala:251)
> 	at scala.util.Success.map(Try.scala:209)
> 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
> 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
> 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
> 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
> 	at tiscaf.sync.SyncQuExecutionContext$$anon$1.run(SyncQuExecutionContext.scala:69)
> Caused by: java.lang.ClassNotFoundException: info.kwarc.mmt.api.Rule$class
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 43 more

**Comment by freifrauvonbleifrei** [comment]
Seems to be solved alongside [issue 303](https://github.com/UniFormal/MMT/issues/303)
