### ISSUE TITLE
Calling MMTSyntaxPresenter on a view throws "semantic object not found"

### ISSUE THREAD

**Issue by ComFreek** [UniFormal/MMT#429]
I want to present a view in MMT surface syntax using `MMTSyntaxPresenter`.

### Code
```scala
val ctrl = new Controller()
ctrl.report.addHandler(ConsoleHandler)
ctrl.extman.addExtension(new info.kwarc.mmt.lf.Plugin())

ctrl.addArchive(ctrl.getHome / "archives" / "MathHub" / "MMT" / "examples")
val archive: Archive = ctrl.backend.getArchive("MMT/examples").get

// Trigger reading all content into memory
archive.allContent
archive.readRelational(FilePath("/"), ctrl, "rel")

implicit val renderingHandler: StringBuilder = new StringBuilder()

val presenter = new MMTSyntaxPresenter()
ctrl.extman.addExtension(presenter)

val view = DPath(URI("http://cds.omdoc.org/examples")) ? "Regular2LeftRegular1"
presenter(ctrl.get(view).asInstanceOf[View])
println(renderingHandler.get)
```

### Error

```none
user: opened archive <...>\archives\MathHub\MMT\urtheories
user: ... with realizations in folder <...>\archives\MathHub\MMT\urtheories\bin
user: opened archive <...>\archives\MathHub\MMT\examples
user: ... with realizations in folder <...>\archives\MathHub\MMT\examples\bin

  error: (library) implicit morphism http://cds.omdoc.org/examples?Regular2LeftRegular1 from http://cds.omdoc.org/urtheories?TermsTypesKinds to http://cds.omdoc.org/examples?LeftRegular1 induced by http://cds.omdoc.org/examples?Regular2LeftRegular1 in conflict with existing implicit morphism (http://cds.omdoc.org/urtheories?ModExp?composition)


Exception in thread "main" invalid object (semantic object not found): scala://lf.mmt.kwarc.info?NormalizeCurrying
	at info.kwarc.mmt.api.symbols.RuleConstantInterpreter.$anonfun$createRule$2(RuleConstant.scala:59)
	at scala.Option.getOrElse(Option.scala:138)
	at info.kwarc.mmt.api.symbols.RuleConstantInterpreter.createRule(RuleConstant.scala:59)
	at info.kwarc.mmt.api.symbols.RuleConstantInterpreter.apply(RuleConstant.scala:93)
	at info.kwarc.mmt.api.backend.XMLReader.readInModuleAux(ReadXML.scala:309)
	at info.kwarc.mmt.api.backend.XMLReader.readInModule(ReadXML.scala:182)
	at info.kwarc.mmt.api.backend.XMLReader.readIn(ReadXML.scala:82)
	at info.kwarc.mmt.api.backend.XMLStreamer$ConsParser.elem(StreamXML.scala:230)
	at scala.xml.parsing.MarkupParser.element1(MarkupParser.scala:593)
	at scala.xml.parsing.MarkupParser.element1$(MarkupParser.scala:573)
	at scala.xml.parsing.ConstructingParser.element1(ConstructingParser.scala:48)
	at scala.xml.parsing.MarkupParser.content1(MarkupParser.scala:433)
	at scala.xml.parsing.MarkupParser.content1$(MarkupParser.scala:419)
	at scala.xml.parsing.ConstructingParser.content1(ConstructingParser.scala:48)
	at scala.xml.parsing.MarkupParser.content(MarkupParser.scala:459)
	at scala.xml.parsing.MarkupParser.content$(MarkupParser.scala:442)
	at scala.xml.parsing.ConstructingParser.content(ConstructingParser.scala:48)
	at scala.xml.parsing.MarkupParser.element1(MarkupParser.scala:588)
	at scala.xml.parsing.MarkupParser.element1$(MarkupParser.scala:573)
	at scala.xml.parsing.ConstructingParser.element1(ConstructingParser.scala:48)
	at scala.xml.parsing.MarkupParser.content1(MarkupParser.scala:433)
	at scala.xml.parsing.MarkupParser.content1$(MarkupParser.scala:419)
	at scala.xml.parsing.ConstructingParser.content1(ConstructingParser.scala:48)
	at scala.xml.parsing.MarkupParser.content(MarkupParser.scala:459)
	at scala.xml.parsing.MarkupParser.content$(MarkupParser.scala:442)
	at scala.xml.parsing.ConstructingParser.content(ConstructingParser.scala:48)
	at scala.xml.parsing.MarkupParser.element1(MarkupParser.scala:588)
	at scala.xml.parsing.MarkupParser.element1$(MarkupParser.scala:573)
	at scala.xml.parsing.ConstructingParser.element1(ConstructingParser.scala:48)
	at scala.xml.parsing.MarkupParser.content1(MarkupParser.scala:433)
	at scala.xml.parsing.MarkupParser.content1$(MarkupParser.scala:419)
	at scala.xml.parsing.ConstructingParser.content1(ConstructingParser.scala:48)
	at scala.xml.parsing.MarkupParser.document(MarkupParser.scala:247)
	at scala.xml.parsing.MarkupParser.document$(MarkupParser.scala:225)
	at scala.xml.parsing.ConstructingParser.document(ConstructingParser.scala:48)
	at info.kwarc.mmt.api.backend.XMLStreamer.apply(StreamXML.scala:74)
	at info.kwarc.mmt.api.checking.OneStepInterpreter.apply(Interpreter.scala:116)
	at info.kwarc.mmt.api.frontend.Controller.read(Controller.scala:286)
	at info.kwarc.mmt.api.backend.Storage.loadXML(Storage.scala:22)
	at info.kwarc.mmt.api.archives.Archive.load(Archive.scala:88)
	at info.kwarc.mmt.api.backend.Backend.$anonfun$load$2(Backend.scala:59)
	at info.kwarc.mmt.api.backend.Backend.$anonfun$load$2$adapted(Backend.scala:55)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at info.kwarc.mmt.api.backend.Backend.load(Backend.scala:55)
	at info.kwarc.mmt.api.frontend.Controller.$anonfun$retrieve$2(Controller.scala:450)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at info.kwarc.mmt.api.frontend.Logger.logGroup(Log.scala:34)
	at info.kwarc.mmt.api.frontend.Logger.logGroup$(Log.scala:31)
	at info.kwarc.mmt.api.frontend.Controller.logGroup(Controller.scala:73)
	at info.kwarc.mmt.api.frontend.Controller.retrieve(Controller.scala:447)
	at info.kwarc.mmt.api.frontend.Controller.$anonfun$iterate$2(Controller.scala:437)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at info.kwarc.mmt.api.frontend.Controller.iterate(Controller.scala:425)
	at info.kwarc.mmt.api.frontend.Controller.iterate(Controller.scala:437)
	at info.kwarc.mmt.api.frontend.Controller.iterate(Controller.scala:415)
	at info.kwarc.mmt.api.frontend.Controller$$anon$1.forDeclarationsInScope(Controller.scala:330)
	at info.kwarc.mmt.api.RuleSet$.$anonfun$collectAdditionalRules$2(Rule.scala:141)
	at info.kwarc.mmt.api.RuleSet$.$anonfun$collectAdditionalRules$2$adapted(Rule.scala:140)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at info.kwarc.mmt.api.RuleSet$.collectAdditionalRules(Rule.scala:140)
	at info.kwarc.mmt.api.RuleSet$.collectRules(Rule.scala:129)
	at info.kwarc.mmt.api.uom.ElaborationBasedSimplifier.applyElementBeginWithParent(ElaborationBasedSimplifier.scala:88)
	at info.kwarc.mmt.api.uom.ElaborationBasedSimplifier.applyWithParent(ElaborationBasedSimplifier.scala:68)
	at info.kwarc.mmt.api.uom.ElaborationBasedSimplifier.applyChecked(ElaborationBasedSimplifier.scala:60)
	at info.kwarc.mmt.api.uom.StructureSimplifier.apply(Simplifier.scala:44)
	at info.kwarc.mmt.api.uom.StructureSimplifier.apply$(Simplifier.scala:44)
	at info.kwarc.mmt.api.uom.Simplifier.apply(Simplifier.scala:63)
	at info.kwarc.mmt.api.presentation.MMTStructurePresenter.apply(MMTStructurePresenter.scala:26)
	at info.kwarc.test.playground.ViewTest$.main(ViewTest.scala:26)
	at info.kwarc.test.playground.ViewTest.main(ViewTest.scala)

Process finished with exit code 1
```

### Debugging

[`RuleConstantInterpreter#createRule`](https://github.com/UniFormal/MMT/blob/b75848a5abe63f2931117696025ecc0f87e04472/src/mmt-api/src/main/info/kwarc/mmt/api/symbols/RuleConstant.scala#L52) searches for the rule `[UnivTerm] : scala://lf.mmt.kwarc.info?UnivTerm` and then calls [`ExtensionManager#addExtensionO`](https://github.com/UniFormal/MMT/blob/b75848a5abe63f2931117696025ecc0f87e04472/src/mmt-api/src/main/info/kwarc/mmt/api/frontend/ExtensionManager.scala#L226) with `cls="info.kwarc.mmt.lf.UnivTerm", args=List()`, which in turn cannot find the specified class.

I speculate that I still to need some extension, but I could not determine which one by browsing through this GitHub repo (searching for `UnivTerm`) or looking at other controller-bootstrapping files.

**Comment by ComFreek** [comment]
[Continuing the conversation we had in person] @Jazzpirate Sadly, even with urtheories, examples and rebuilt MMT at their latest devel commits (as of now), I get the same errors.

**Comment by ComFreek** [comment]
Now it works. Probably this is due to me rebuilding all archives with `-mmt-omdoc, -scala-bin, scala-bin, mmt-omdoc` (in that order!)
Archives usually come with compiled Scala files pre-committed, so if the Scala version the user uses does not match, it might lead to error such as this issue.

--> Should archives come with committed binary files?
--> Document how archives are built, see also https://github.com/UniFormal/uniformal.github.io/wiki/Issues#documentation-on-how-to-build-archives-w-or-wo-scala-sources

Credits for incompatible binary files being the origin of the issue go to @Jazzpirate.
