### ISSUE TITLE
MMT crashes when path contains space

### ISSUE THREAD

**Issue by ux51ekac** [UniFormal/MMT#574]
MMT currently crashes with the following error _on linux_ when the path where the jar is located contains a space. #222 might be related.

```
Exception in thread "main" general error: cannot find resource /mmtrc (run style is Classes(/home/local/source/MMT%20test/deploy/mmt.jar))
	at info.kwarc.mmt.api.utils.MMTSystem$.getResourceAsString(System.scala:133)
	at info.kwarc.mmt.api.frontend.Controller.init(Controller.scala:218)
	at info.kwarc.mmt.api.frontend.Controller.<init>(Controller.scala:222)
	at info.kwarc.mmt.api.frontend.Shell.controller$lzycompute(Shell.scala:50)
	at info.kwarc.mmt.api.frontend.Shell.controller(Shell.scala:50)
	at info.kwarc.mmt.api.frontend.Shell.main(Shell.scala:61)
	at info.kwarc.mmt.api.frontend.Run.main(Shell.scala)
```

is there a reason why MMT is handling treating an URL as a file path [here](https://github.com/UniFormal/MMT/blob/213a3836a2ff517c6962f9d0c26cd1b02e325fc8/src/mmt-api/src/main/info/kwarc/mmt/api/utils/System.scala#L49) ?
otherwise a possible fix would be to decode the url back to an unencoded path string:

```scala
val classFolder = File(URLDecoder.decode(location.getPath, StandardCharsets.UTF_8))
```

**Comment by ux51ekac** [comment]
this also seems to happen for paths with other url encoded symbols eg. german umlauts
